### ISSUE TITLE
Modularisation: is really necessary?

### ISSUE THREAD

**Issue by NickNaso** [NickNaso/hertzy#11]
Is really necessary split the actual code? We have not more LOC, but if we need to add other features in the future maybe this could be a starting point. What do you think about?

**Comment by mauro-d** [comment]
I've started a simple modularization.
Yes, it's probably not strictly necessary but there is some work done in this [branch](https://github.com/mauro-d/hertzy/tree/hertz-factor), so this task will not require a big effort.

**Comment by NickNaso** [comment]
I agree and I think that the changes need to be direct consequences of all the necessary task to solve the issue: **[https://github.com/NickNaso/hertzy/issues/10](https://github.com/NickNaso/hertzy/issues/10)**
