### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NickNaso** [NickNaso/hertzy#9]
We need to create a new logo for the project. Please post here any ideas, but my my opinion is to let the hands free to @Govee91 to accomplish at this task.

**Comment by ggcarlosr** [comment]
Hello brother, I am a graphic designer, and I make free contributions for open source projects I would like to help you, let me know your requirements, features of the app and if you have in mind as shapes or colors that you would like to see in the proposal, leave Free layout of the designer any idea? I await your prompt reply. Thanks

**Comment by mauro-d** [comment]
Hi @ggcarlosr, i would say thank you very much for your offer, but at the moment @Govee91 is already working on this. Anyway, if you are interested, we will keep in mind you for future projects.

Thanks again!

Mauro

**Comment by NickNaso** [comment]
Hi @Govee91  could you provide the first draft of the logo for Monday 4th June?

**Comment by NickNaso** [comment]
Ping @Govee91

**Comment by NickNaso** [comment]
Good work @Govee91
